version: '3.8'
services:
  pgbouncer:
    image: tarsil/django:latest
    depends_on:
      - db
    environment:
      ENVIRONMENT: development
      ROLE: pgbouncer
    links:
      - db:postgres
    expose:
      - 6432
    ports:
      - 6432:6432
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: bash -lc "pip3 install invoke jinja2 markupsafe==2.0.1 && invoke -r /var/www/roles $${ROLE}"

  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    volumes:
      - "{{ cookiecutter.project_name }}_db_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379

  rabbitmq:
    restart: always
    image: rabbitmq:3.8.5
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_user_default_pass
      RABBITMQ_DEFAULT_VHOST: /
    expose:
      - 15672
      - 5672
    ports:
      - 5672:5672
      - 15672:15672

  {%if cookiecutter.without_mongo == "N" -%}
    mongodb:
      restart: always
      image: mongo:latest
      container_name: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mongoadmin
        MONGO_INITDB_DATABASE: mongodb
      volumes:
          - "{{ cookiecutter.project_name }}_mongo_db_data:/data/db"
      expose:
        - 27017
      ports:
        - 27017:27017

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: password
  {% endif %}

volumes:
  {{ cookiecutter.project_name }}_db_data:
    external: true
  {% if cookiecutter.without_mongo == "N"-%}
  {{ cookiecutter.project_name }}_mongo_db_data:
      external: true
  {% endif %}
