version: "3.8"
services:
  db:
    image: postgres:12.3
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.8.5
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_user_default_pass
      RABBITMQ_DEFAULT_VHOST: /
    expose:
      - 15672
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
